name: powersync_flutter_demo
description: PowerSync Flutter Demo
publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  powersync: ^0.4.2
  path_provider: ^2.1.1
  supabase_flutter: ^1.10.25
  path: ^1.8.3
  logging: ^1.2.0
  sqlite_async: ^0.5.2
  camera: ^0.10.5+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
